language: bash

sudo: required
dist: trusty

services:
- docker

env:
- ORGANIZATION=${DOCKER_USER} JAVA_VERSION='java-11-openjdk'    REPO='s2i-builder-maven' TAG='latest'
- ORGANIZATION=${DOCKER_USER} JAVA_VERSION='java-11-openjdk'    REPO='s2i-builder-maven' TAG='11'
- ORGANIZATION=${DOCKER_USER} JAVA_VERSION='java-1.8.0-openjdk' REPO='s2i-builder-maven' TAG='8'

script:
- docker build -t ${ORGANIZATION}/${REPO}:${TAG} --build-arg JAVA_VERSION=${JAVA_VERSION} --no-cache .
# security check
- .travis/security-scan.sh ${ORGANIZATION}/${REPO}:${TAG}
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    docker push ${ORGANIZATION}/${REPO}
  fi